### ISSUE TITLE
VersionInfo message ignores max-version if reconnected from proxy or logging in before server finalized.

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaRewind-Legacy-Support#44]
Paper dev 28 (Spigot 1.19)
Waterfall dev 496 (BungeeCord 1.19)

(Plugins on Server)
ViaVersion dev 617
ViaBackwards dev 271
ViaRewind dev 127
ViaRewind Legacy Support dev 19

(Plugin on Proxy)
Bungee-Reconnect 1.6.0

```
versioninfo:
  active: true
  max-version: 758
  interval: JOIN
  message: '&7[&6Info&7] This server is running Minecraft %version%. The best gameplay
    experience is only guaranteed if you are using this version.'
```

I have VersionInfo configured to message all clients that connect below MC 1.19 to inform them to update. If I login to the server normally through the disconnected main multiplayer menu (Main Menu -> BungeeCord -> Paper), the login payload correctly detects the client version and _doesn't_ send the version info message to my 1.19 client.

If I restart my server and have the client idle on the proxy until the server is back up, when the client is automatically sent back to the server from the proxy once it is done, VersionInfo message gets sent to the client. Is the login payload not sending the version to the plugin?

Likewise, I also noticed if I restart both my server & proxy at the same time and connect to the server fresh while it's doing initial initialization, where you are stuck "logging in" until the server startup status is ``done``, VersionInfo sends the message when you finally connect.

Could both issues be related to VersionInfo not initializing fast enough? Is this fixable? If not, is it possible to not default to sending the message if it doesn't get the player's game version protocol?
